#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/nginx"

echo "[$APPNAME][$(date)] Nginx started as an s6 service"

# -----------------------------------------------------------------------------------
# Copyright 2020, 2021 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/docker-planefence
#
# -----------------------------------------------------------------------------------
#
# We are running nginx in the foreground. If, for any reason, it fails, we wait 10 seconds
# to make sure we're not spamming the processor with restarts, and then we run it again.
while true
do
    /usr/sbin/nginx -g 'daemon off;'
    sleep 10
done
