#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/php7.3-fpm"

echo "[$APPNAME][$(date)] php7.3-fpm started as an s6 service"

# -----------------------------------------------------------------------------------
# Copyright 2020, 2021 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/docker-planefence
#
# -----------------------------------------------------------------------------------
#
# If the run directory doesn't exist, create it. This directory will contain the PHP socket.
# (It's supposed to be created by the Dockerfile, but docker-compose definitions
#  of /run as tmpfs overwrites any build-time installs in that directory tree.)
#
mkdir -p /run/php
#
# We are running php7.3-fpm in the foreground. If, for any reason, it fails, we wait 10 seconds
# to make sure we're not spamming the processor with restarts, and then we run it again.
#
while true
do
    /usr/sbin/php-fpm7.3 --nodaemonize --fpm-config /etc/php/7.3/fpm/php-fpm.conf
    sleep 10
done
